version: "3.7"
services:           
    otel-collector:
      image: otel/opentelemetry-collector-contrib-dev:latest
      command: ["--config=/etc/otel-collector-config.yaml", ""]
      volumes:
        - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      ports:
        - "8888:8888"   # Prometheus metrics exposed by the collector
        - "8889:8889"   # Prometheus exporter metrics
        - "13133:13133" # health_check extension
        - "14268:14268"
        - "4317:4317"        # OTLP gRPC receiver
        - "4318:4318"        # OTLP http receiver
      networks:
        - service_bridge

    # server:
    #     build: 
    #         context: ./client
    #         dockerfile: Dockerfile
    #     env_file: ./server/.env
    #     ports:
    #         - "8080:8000"   
    #     deploy:
    #         restart_policy:
    #             condition: on-failure

    #     networks:
    #         - service_bridge  

    # ubuntu:
    #     build: 
    #         context: ./ubuntu
    #         dockerfile: Dockerfile
    #     #entrypoint: "sleep"
    #     command: "3000"
    #     networks:
    #         - service_bridge

networks:
    service_bridge:
        driver: bridge