receivers:
  otlp:
    protocols:
      grpc: # on port 4317

  # hostmetrics:
  #   scrapers:
  #     cpu:
  #     disk:
  #     filesystem:
  #     load:
  #     memory:
  #     network:
  #     process:
  #     processes:
  #     paging:

processors:
  batch:

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_APIKEY}"
      "x-honeycomb-dataset": "${HONEYCOMB_SERVICENAME}"

  otlp/metrics:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_APIKEY}"
      "x-honeycomb-dataset": "${HONEYCOMB_METRICS_DATASET}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

    metrics:
      receivers: [otlp]
      #receivers: [hostmetrics, otlp]
      processors: []
      exporters: [otlp/metrics]

  telemetry:
    logs:
      level: "debug"
