receivers:
  otlp:
    protocols:
      grpc: # on port 4317

processors:
  batch:

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_APIKEY}"
      "x-honeycomb-dataset": "${HONEYCOMB_SERVICENAME}"

  otlp/metrics:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_APIKEY}"
      "x-honeycomb-dataset": "${HONEYCOMB_METRICS_DATASET}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

    metrics:
      #receivers: [hostmetrics,prometheus]
      receivers: [otlp]
      processors: []
      exporters: [otlp/metrics]

  telemetry:
    logs:
      level: "debug"
