services:           
    collector:
      image: otel/opentelemetry-collector-contrib:0.50.0
      command: ["--config=/etc/otel-collector-config.yaml", ""]
      volumes:
        - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      ports:
        - "1888:1888"   # pprof extension
        - "8888:8888"   # Prometheus metrics exposed by the collector
        - "8889:8889"   # Prometheus exporter metrics
        - "13133:13133" # health_check extension
        - "4317:4317"        # OTLP gRPC receiver
        - "4318:4318"        # OTLP http receiver
        - "55670:55679" # zpages extension
      networks:
        - service_bridge  
      profiles: [all, collector, collectoronly]         
        
    tracing:
      build: 
        context: ./client
        dockerfile: Dockerfile
      environment:
        - HONEYCOMB_SERVICENAME=10_script_tracing
        - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4317            
        - DATE_COMMAND=date
      command: "/workbench/test-cli.sh"         
      depends_on:
        - collector           
      networks:
        - service_bridge
      profiles: [all, collector]      

    tracing-no-collector:
      build: 
        context: ./client
        dockerfile: Dockerfile
      environment:
        - HONEYCOMB_SERVICENAME=10_script_tracing     
        - DATE_COMMAND=date
      command: "/workbench/test-cli-direct.sh"        
      depends_on:
        - collector           
      networks:
        - service_bridge
      profiles: [all, nocollector]     

networks:
    service_bridge:
        driver: bridge